writen-report
geekan/MetaGPT pull request #1235
Opened 2024-04-29 03:54 UTC by wangwenju269

**Features**

- xx
- yy
    
**Feature Docs**

**Influence**

**Result**

**Other**

2024-04-30 03:18 UTC, wangwenju269 commented
按照返回意见，重新修改代码，清晰。对 原 Metagpt 结构 未作任何改变， 复用源基层代码， 模仿datainterpreter 类进行改造，实现与源代码 高耦合。

2024-04-30 03:25 UTC, geekan commented
Great! Let's review

2024-05-06 06:21 UTC, wangwenju269 commented
I developed an official document writing artifact, which can be expanded to the fields of paper writing, official document generation, bidding documents and other fields according to user needs. In the future, tools such as networking and literature retrieval will continue to be integrated. The code repository is at: METAGPT\tests\metagpt\ext\write_report\report.py
(我开发一款公文写作神器， 根据用户的需求可以拓展到论文写作，公文生成，招投标文档等领域。后续会继续集成 联网，文献检索等工具。代码仓库在： METAGPT\tests\metagpt\ext\write_report\report.py)

2024-05-17 03:05 UTC, shenchucheng commented
@wangwenju269 哈喽，有一些问题先请问下
1. 为什么代码是写在tests目录下？
2. 我看大部分的提示词都是中文，是必须使用中文提示词，还是什么原因呢？

2024-05-17 03:42 UTC, wangwenju269 commented
您好：

答复如下

       问题1 ： 放在 test 路径下的目的：自己开发的项目代码脚本 和 源metagpt框架 能更好解耦，本项目是复用 metagpt 现有的类和方法，代码做到高内聚，低耦合。

       问题2： 提示词是可以拓展的，已将提示词单独放在一个文件里。后续更换提示词文件，实现实现招投标、论文写作等应用场景。 提示词是可插拔替换的，根据具体业务场景，更换提示词

      







祝好！







在 2024-05-17 11:06:18，"shenchucheng" ***@***.***> 写道：

@wangwenju269 哈喽，有一些问题先请问下

为什么代码是写在tests目录下？
我看大部分的提示词都是中文，是必须使用中文提示词，还是什么原因呢？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-17 04:31 UTC, wangwenju269 commented
有修改意见，请及时反馈给我，谢谢

2024-05-17 09:00 UTC, garylin2099 commented
> 您好： 答复如下 问题1 ： 放在 test 路径下的目的：自己开发的项目代码脚本 和 源metagpt框架 能更好解耦，本项目是复用 metagpt 现有的类和方法，代码做到高内聚，低耦合。 问题2： 提示词是可以拓展的，已将提示词单独放在一个文件里。后续更换提示词文件，实现实现招投标、论文写作等应用场景。 提示词是可插拔替换的，根据具体业务场景，更换提示词 祝好！ 在 2024-05-17 11:06:18，"shenchucheng" ***@***.***> 写道： @wangwenju269 哈喽，有一些问题先请问下 为什么代码是写在tests目录下？ 我看大部分的提示词都是中文，是必须使用中文提示词，还是什么原因呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

metagpt下有ext文件夹（external, extension之意），可将代码放入metagpt/ext下，参考stanford_town的放置方法，可与metagpt核心代码相分开

2024-05-17 09:32 UTC, garylin2099 reviewed
代码虽然集成了MG内DataInterpreter, WritePlan, Planner等类，但仍不免需要改写大量函数，子类函数与父类函数有较多重复。这并非此PR的问题，是原来DI及DI相关类未留出足够的可配置项。若从此PR出发，可以再仔细考虑，哪些地方是可以直接使用原DI代码，哪些是必须要自定义，尽量减少些重复

2024-05-17 09:32 UTC, garylin2099 commented on tests/metagpt/ext/write_report/core_report.py
> +class RewriteReport(Role):
应为ReportRewriter，RewriteReport是动作的意思

2024-05-17 09:32 UTC, garylin2099 commented on config/config2.yaml
> +  model: "qwen-14B-Chat"  # or gpt-3.5-turbo
这个改动不应该提交

2024-05-17 09:32 UTC, garylin2099 commented on tests/metagpt/ext/write_report/report.py
> +    await di.run(f"{requirement}", upload_file="E:\workspace\MetaGPT\data\“5.18”金达花园三期项目坍塌事故调查报告.json")
建议去掉具体的路径名和文件名

2024-05-17 09:32 UTC, garylin2099 commented on tests/metagpt/ext/write_report/write_evaluator_refine.py
> +def process_message(messages: Union[str, Message, list[dict], list[Message], list[str]]) -> list[dict]:
可使用llm.format_msg，见具体provider文件

2024-05-17 09:32 UTC, garylin2099 commented on tests/metagpt/ext/write_report/write_evaluator_refine.py
> +STRUCTUAL_PROMPT = """
可跟write_analysis_code.py保持一致，将prompt放入单独文件

2024-05-17 09:32 UTC, garylin2099 commented on tests/metagpt/ext/write_report/write_report_planner.py
> +            rsp = CodeParser.parse_code(block=None, text=rsp)
可改写PROMPT_TEMPLATE，这段使用super().run

2024-05-17 09:32 UTC, garylin2099 commented on tests/metagpt/ext/write_report/write_report_planner.py
> +    def get_plan_status(self) -> str:
这个函数是否需要改写？PLAN_STATUS待填入的变量名可以和原PLAN_STATUS保持一致

2024-05-17 09:32 UTC, garylin2099 commented on tests/metagpt/ext/write_report/write_report_planner.py
> +class WritePlanner(Planner):
WriteReportPlanner

2024-05-24 08:08 UTC, wangwenju269 commented on tests/metagpt/ext/write_report/write_report_planner.py
> +            rsp = CodeParser.parse_code(block=None, text=rsp)
不大认可，super().run函数里有TaskType这个枚举类型。在不改变源代码接触上，我之前考虑重新设置UserTaskType，但还需要外层封装一下，因此将 UserTaskType 里的内容卸载外部 yaml 文件里。

2024-05-24 08:10 UTC, wangwenju269 commented on tests/metagpt/ext/write_report/write_evaluator_refine.py
> +STRUCTUAL_PROMPT = """
这只是提示词应用模板，且是通用的，没必要存在单独文件里。

2024-05-24 08:11 UTC, wangwenju269 commented on tests/metagpt/ext/write_report/report.py
> +    await di.run(f"{requirement}", upload_file="E:\workspace\MetaGPT\data\“5.18”金达花园三期项目坍塌事故调查报告.json")
好的

2024-05-24 08:12 UTC, wangwenju269 commented on config/config2.yaml
> +  model: "qwen-14B-Chat"  # or gpt-3.5-turbo
只是为了接开源模型测试代码是否通过

2024-05-24 08:18 UTC, wangwenju269 commented on tests/metagpt/ext/write_report/write_report_planner.py
> +    def get_plan_status(self) -> str:
是的，之前我想复用来着，后来取消 TaskType 这个类的使用，就不能直接访问其中的方法了，就简单重写了

2024-05-24 08:21 UTC, wangwenju269 commented on tests/metagpt/ext/write_report/write_evaluator_refine.py
> +def process_message(messages: Union[str, Message, list[dict], list[Message], list[str]]) -> list[dict]:
METAgpt 版本代码 更新速度有点快，二次开发不一定能跟上。

2024-05-24 08:27 UTC, wangwenju269 commented
答复：文件放置在 test 目录下，方便更好测试代码是否独立执行成功。
      我已遵循评审大佬的要求和反馈建议，做出相应修改，清再次查收。
      祝好！

2024-05-29 08:42 UTC, shenchucheng requested changes

2024-05-29 08:42 UTC, shenchucheng commented on config/config2.yaml
> +  model: "qwen-14B-Chat"  # or gpt-3.5-turbo
建议恢复到原先的改动：
![image](https://github.com/geekan/MetaGPT/assets/60704484/3dbf7fe7-5db1-410e-bcc4-c018076d8b04)
本地测试时，使用~/.metagpt/config2.yaml文件进行配置

2024-08-19 02:32 UTC, closed without merging